### ISSUE TITLE
Mailu OIDC - Authelia

### ISSUE THREAD

**Issue by wawefr** [heviat/Mailu#7]
Hello 
I discover with lots of pleasure Mailu-OIDC.
I start a mailu serveur which is ok, my point now is to use OIDC connection via my Authelia (my OIDC serveur).
I have configured Mailu with OIDC, and it redirects correctly to Authelia, but I have to re-enter my username and password on Authelia (not good)  After authentication, I get a "strong user or pwd" message.
 I feel like the communication between Mailu OIDC and Authelia isn't working properly. 
I am attaching my mailu.env OIDC configuration file. 
If you have any ideas, I would appreciate it
Thansk Fred 

mailu.env extract

```properties
###################################
# OpenID Connect settings
###################################

# Enable OpenID Connect. Possible values: True, False
OIDC_ENABLED=true
# OpenID Connect Provider configuration URL
OIDC_PROVIDER_INFO_URL=https://authv2.*******mydomain
# OpenID redirect URL if HOSTNAME not matching your login url
OIDC_REDIRECT_URL=https://mail.***mydomain
# OpenID Connect Client id
OIDC_CLIENT_ID=mailu
# OpenID Connect Client secret
OIDC_CLIENT_SECRET=*******
# Display text for OpenID Connect login button. Default: OpenID Connect
OIDC_BUTTON_NAME=OpenID Connect
OIDC_VERIFY_SSL=true
OIDC_CHANGE_PASSWORD_REDIRECT_ENABLED=true
OIDC_CHANGE_PASSWORD_REDIRECT_URL=https://authv2.***mydomain/reset-password/step1
LD_PRELOAD=/usr/lib/libhardened_malloc.so
```

authelia config extract

```yaml
      - client_id: 'mailu'
        client_name: 'mailu'
        client_secret: '*******'
        consent_mode: implicit
        scopes:
          - openid
          - email
          - profile
        redirect_uris:
          - 'https://mail.***mydomain/sso/login'
        token_endpoint_auth_method: 'client_secret_post
```
